# Generated by Django 5.2.6 on 2025-10-27 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_remove_user_full_name'),
        ('receptionist_app', '0002_patient_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billing',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_created', to='admin_app.staff'),
        ),
    ]
