# Generated by Django 5.2.6 on 2025-10-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinebilling',
            name='medicines',
        ),
    ]
