# Generated by Django 5.2.7 on 2025-10-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='diagnosis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='symptoms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
