# Generated by Django 5.2.6 on 2025-10-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0003_alter_consultation_diagnosis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='medicine',
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='medicine_name',
            field=models.CharField(default='Unknown Medicine', max_length=200),
        ),
    ]
